### PR TITLE
Add section about updating the documentation

### PR DESCRIPTION
**Pull request by tomi**
Add documentation how to update the database documentation using the `--force` flag.

### CODE REVIEW

**Comment by k1LoW** [comment]
Thank you for your commit!

I think 

- `--force` flag is not for updates, it's just an option to force overwrite of the document. For example, the md file of a table that has been removed from the data source will not be removed by `--force`.
- `--rm-dist` flag removes all files in the document path. It is not a flag for updating.

This means that tbls does not currently have the features to update the document correctly yet.

**Review by k1LoW — CHANGES_REQUESTED** [review]
https://github.com/k1LoW/tbls/pull/287#issuecomment-771268627

**Comment by tomi** [comment]
I updated the README to describe these flags

**Comment by k1LoW** [comment]
@tomi GREAT!!! THANK YOU!!

**Review by k1LoW — APPROVED** [review]

**Pull request merged**
