### PR TITLE
Hide `parent`, `children`, `comment` columns without data

### PR DESCRIPTION
**Pull request by YauhenPylAurea**
Fix for https://github.com/k1LoW/tbls/issues/321

thank you for the great tool!

it feels like it is possible to make reports more readable by removing columns with no data.

### CODE REVIEW

**Comment by k1LoW** [comment]
Thanks for the great pull request.
My current opinions on the additional features are

1. We are concerned that the table formatting will change on a table-by-table basis, which will increase the cognitive load.
    - I expect that the presence or absence of relations and comments will change at a different frequency than Extra Definition in MySQL.
2. I believe documentation is important. Therefore, I would like to be able to tell by an appearance that comments have not been written. (I also think foreign key constraints are a bit important)

I think it is a great feature.
Just that my opinion at this point is the above.

**Comment by k1LoW** [comment]
Maybe my opinion could change in the future.

**Comment by awhitford-cip** [comment]
> 1. We are concerned that the table formatting will change on a table-by-table basis, which will increase the cognitive load.

Snowflake doesn't have parent/child metadata, so that could be a database/connection setting (not unique per table).

**Comment by YauhenPylAurea** [comment]
perhaps we can do it as an option. what do you thing @k1LoW ?

**Comment by k1LoW** [comment]
@YauhenPylAurea Great!!! I had not thought of it at all.

I wanted to add a new section to .tbls.yml.

**Comment by YauhenPylAurea** [comment]
@k1LoW I am not sure what is the best format for such thing in `.tbls.yml`. Should it be under `format`?
```
# .tbls.yml
format:
  # Adjust the column width of Markdown format table
  # Default is false
  adjust: true
  # Sort the order of table list and columns
  # Default is false
  sort: false
  # Display sequential numbers in table rows
  # Default is false
  number: false
  # The comments for each table in the Tables section of the index page will display the text up to the first double newline (first paragraph).
  # Default is false
  showOnlyFirstParagraph: true
  # Hide columns without data
  hideColumnsWithoutData: ["Comment","Parents","Children"]
```
???

**Comment by k1LoW** [comment]
```yaml
format:
  hideColumnsWithoutData: ["Comment","Parents","Children"]
```

I think it is very good.

Now we just need to decide whether to also allow bool values, as follows

```yaml
format:
  hideColumnsWithoutData: true
```

**Comment by YauhenPylAurea** [comment]
What does it mean in such case?
```
format:
  hideColumnsWithoutData: true
```
Any column without data should be hidden, right?

**Comment by k1LoW** [comment]
In the case of an array ( `hideColumnsWithoutData: ["Comment","Parents","Children"]` ), it allows specifying the columns to be hidden.
If `true` ( `hideColumnsWithoutData: true` ), all columns supported to be hidden will be hidden.

The reason why I want to support boolean values is that tbls can change the column names and I think the user will not remember the column names.

**Comment by k1LoW** [comment]
How about I handle the implementation of https://github.com/k1LoW/tbls/pull/346#issuecomment-1116945602 ?

**Review by k1LoW — APPROVED** [review]

**Comment by k1LoW** [comment]
@YauhenPylAurea It took a while, but the great features you added have been released as v1.56.0. THANK YOU!!!

**Pull request merged**
